# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXuEgIm6gN8PkbbUplroFesFAO99jd02
"""

import pandas as pd
import matplotlib.pyplot as plt
import re
from collections import Counter

df = pd.read_csv("/content/comments.csv")

positive_words = ["good", "great", "excellent", "amazing", "love", "happy"]
negative_words = ["bad", "terrible", "awful", "hate", "sad", "worst"]

def get_simple_sentiment(text):
    text = str(text).lower()
    if any(word in text for word in positive_words):
        return "Positive"
    elif any(word in text for word in negative_words):
        return "Negative"
    else:
        return "Neutral"

df["sentiment_category"] = df["comment"].apply(get_simple_sentiment)

plt.figure(figsize=(6, 6))
df["sentiment_category"].value_counts().plot(kind="pie", autopct="%1.1f%%", colors=["gray", "red", "green"], startangle=90)
plt.title("Sentiment Distribution of Instagram Comments")
plt.show()

emoji_usage = df["emoji used"].value_counts()
plt.figure(figsize=(6, 4))
emoji_usage.plot(kind="bar", color=["blue", "orange"])
plt.title("Emoji Usage in Comments")
plt.xlabel("Emoji Used")
plt.ylabel("Count")
plt.show()

df["Hashtags used count"] = pd.to_numeric(df["Hashtags used count"], errors='coerce')
plt.figure(figsize=(6, 4))
df["Hashtags used count"].plot(kind="hist", bins=10, color="purple", alpha=0.7)
plt.title("Distribution of Hashtag Usage")
plt.xlabel("Number of Hashtags")
plt.ylabel("Frequency")
plt.show()

if "created Timestamp" in df.columns:
    df["created Timestamp"] = pd.to_datetime(df["created Timestamp"], errors='coerce')
    df["date"] = df["created Timestamp"].dt.date
    comments_per_day = df.groupby("date").size()
    plt.figure(figsize=(8, 4))
    comments_per_day.plot(kind="line", marker="o", color="green")
    plt.title("Number of Comments Over Time")
    plt.xlabel("Date")
    plt.ylabel("Number of Comments")
    plt.xticks(rotation=45)
    plt.show()

plt.figure(figsize=(8, 4))

if 'User  id' in df.columns:
    df["User  id"].value_counts().head(10).plot(kind="bar", color="cyan")
    plt.title("Top 10 Most Active Users")
    plt.xlabel("User ID")
    plt.ylabel("Number of Comments")
    plt.show()
else:
    print("Column 'user_id' not found in DataFrame.")